#!/bin/sh
ls $HOME/.scripts/screenlayout/ | dmenu -l 10 -p "Display Configuration: " | xargs -r -I{} sh $HOME/.scripts/screenlayout/{}
feh --bg-scale '/home/yuvaldahn/Pictures/background.jpg'
polybar_launch
