#!/bin/sh
exec "$@" >> $LOG_POLYBAR 2>&1
killall -q polybar
while pgrep -u $UID -x polybar > /dev/null; do sleep 0.05; done
echo "------- [$(date  --rfc-3339=seconds)] Starting polybar -------"
tray_output=eDP1
for m in $(polybar --list-monitors | cut -d":" -f1); do
    export TRAY_POSITION=none
    if [[ $m == $tray_output ]]; then
        TRAY_POSITION=right
    fi
    MONITOR=$m polybar -l error top &
done
